apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: front-end
        image: 381492031718.dkr.ecr.us-east-1.amazonaws.com/front-end
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://api:3500/api/tasks"
        ports:
        - containerPort: 3000
      # Adding the frontend label for easier extraction
      frontend: 381492031718.dkr.ecr.us-east-1.amazonaws.com/front-end
